title:                  "Chassis - CSS"
baseURL:                "https://chassis-ui.com"

docsDir:                "site"

subtitle:               "A CSS framework which synchronizes with Figma components by using design tokens."
description:            "Chassis - CSS consists of a complete set including Figma components, design tokens and their transformers for multiple products on multiple platforms under the name of multiple brands."
authors:                "Ozgur Gunes and Bootstrap contributers"

current_version:        "0.1.0"
current_ruby_version:   "0.1.0"
docs_version:           "0.1"
rfs_version:            "v10.0.0"
github_org:             "https://github.com/ozgurgunes"
repo:                   "https://github.com/ozgurgunes/chassis-css"
x:                      "chassis_ui"
opencollective:         "https://opencollective.com/chassis"
blog:                   "https://blog.chassis-ui.com/"
themes:                 "https://themes.chassis-ui.com/"
icons:                  "https://icons.chassis-ui.com/"
swag:                   "https://cottonbureau.com/people/chassis"

analytics:
  fathom_site:          "ITUSEYJG"

algolia:
  app_id:                "AK7KMZKZHQ"
  api_key:               "3151f502c7b9e9dafd5e6372b691a24e"
  index_name:            "bootstrap"

download:
  source:               "https://github.com/ozgurgunes/chassis-css/archive/v0.1.0.zip"
  dist:                 "https://github.com/ozgurgunes/chassis-css/releases/download/v0.1.0/chassis-css-0.1.0-dist.zip"
  dist_examples:        "https://github.com/ozgurgunes/chassis-css/releases/download/v0.1.0/chassis-css-0.1.0-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                  "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/css/chassis-css.min.css"
  css_hash:             "sha384-z1z0pR6Kr5Cie6j3tj9zBdR43rQ/19OUDRvLf67MnVBXC2rrIv6KomMcS+7cDrEX"
  css_rtl:              "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/css/chassis-css.rtl.min.css"
  css_rtl_hash:         "sha384-FtQ/A8+7/yGOF6t87QXic08Pn3anj3iAuo948JtneeerUvzL+pfC6vyPu3HRVBlz"
  js:                   "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/js/chassis-css.min.js"
  js_hash:              "sha384-NUR67mCgsLSPLPAkVb32tnNlQdGAfOk/PH4iDWd8UArTrE5mEiDrHmeajFrGm9Up"
  js_bundle:            "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/js/chassis-css.bundle.min.js"
  js_bundle_hash:       "sha384-MKU9WDEVXmku6o36KR2LmSuQ2YKtDx8+/y0rgWX6fbxS8SucAN86y8vVIWKX+uCV"
  popper:               "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  popper_hash:          "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  popper_esm:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
